
var user = {
	REGISTER : 'INSERT INTO USER_INFO(NICK, EMAIL, PASSWORD, STATUS, TYPE, ACCOUNT, CREATE_TIME) VALUES(?,?,?,?,?,?,?)',
	LOGIN : 'SELECT PASSWORD FROM USER_INFO WHERE EMAIL = ?', 
	MODIFY_PASSWORD : 'UPDATE USER_INFO SET PASSWORD=? WHERE EMAIL=?',
	GET_ACCOUNT : 'SELECT ACCOUNT FROM USER_INFO WHERE EMAIL =?',
	BIND_CARD : 'UPDATE USER_INFO SET CARD_ID=? WHERE EMAIL=?',
	INS_ACCOUNT : 'UPDATE USER_INFO SET ACCOUNT=? WHERE EMAIL=?',
	DES_ACCOUNT : 'UPDATE USER_INFO SET ACCOUNT=? WHERE EMAIL=?',
	GET_USER_INFO : 'SELECT * FROM USER_INFO WHERE EMAIL = ?'
};

module.exports = user;
